[pytest]
cache_dir = test-results/backend/.pytest_cache
log_file = ../logs/backend-tests.log
log_file_level = INFO
junit_family = xunit2
addopts = --junitxml=../test-results/backend/pytest-results.xml
